name: cifar10
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.10
  - pip
  - numpy
  - pytorch
  - torchvision
  - torchmetrics
  - jupyterlab
  - typer
  - tqdm
  - loguru
  - onnxruntime
  - onnx
  - pytorch-lightning
  - opencv
  - wandb
  - scikit-image
  - streamlit
  - pip:
    - bentoml
    - redisai
    - ml2rt
